version: '3'

services:
  mysql:
    build:

    image: localhost:5000/mysql
    volumes:
      - ./mysql/setup:/docker-entrypoint-initdb.d
      - ./volumes/testdata/mysql:/testdata
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  phpmyadmin:
      image: localhost:5000/phpmyadmin
      ports:
        - "8888:80"
      links:
        - mysql:mysql
      environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=secret
        - PMA_HOST=mysql
      depends_on:
        - mysql

volumes:
  mysql-data:
    driver: local